### PR TITLE
Add Custom Metrics

### PR DESCRIPTION
**Pull request by serglom21**
# Description

Add custom metrics to the Android demo app. These replicate the same metrics that were added to our react service [here](https://github.com/sentry-demos/empower/pull/376)

- `products_request.duration`
- `checkout.click`
- `checkout.error`
- `checkout.success`

### CODE REVIEW

**Comment by sdzhong** [comment]
Hey @serglom21 , can you please share sample events or their metrics for this PR?

**Comment by serglom21** [comment]
Ah yeah, totally!

- [transaction.duration](https://sergios-test-org.sentry.io/metrics/?interval=4h&project=4506028206850048&statsPeriod=14d) (default)
- [checkout.error](https://sergios-test-org.sentry.io/metrics/?interval=4h&project=4506028206850048&statsPeriod=14d&widgets=%5B%7B%22mri%22%3A%22c%3Acustom%2Fcheckout.error%40none%22%2C%22op%22%3A%22sum%22%2C%22query%22%3A%22%22%2C%22powerUserMode%22%3Afalse%2C%22type%22%3A1%2C%22id%22%3A0%2C%22displayType%22%3A%22line%22%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%2C%22isHidden%22%3Afalse%2C%22overlays%22%3A%5B%22samples%22%5D%7D%5D)(custom)

I do see something _**not**_ working as expected with the [products_request.duration](https://sergios-test-org.sentry.io/metrics/?interval=4h&project=4506028206850048&statsPeriod=14d&widgets=%5B%7B%22mri%22%3A%22d%3Acustom%2Fproducts_request.duration%40millisecond%22%2C%22op%22%3A%22sum%22%2C%22query%22%3A%22%22%2C%22powerUserMode%22%3Afalse%2C%22type%22%3A1%2C%22id%22%3A0%2C%22displayType%22%3A%22line%22%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%2C%22isHidden%22%3Afalse%2C%22overlays%22%3A%5B%22samples%22%5D%7D%5D) metric, where the description for that span is not showing up - I will check on that with the team and follow up!

Screenshot 2024-05-03 at 8 34 42 AM

**Comment by serglom21** [comment]
Mhmm things are not fully working as expected here. Not necessarily because of the code introduced on this PR but rather because of this [issue](https://github.com/getsentry/sentry/issues/70509) that happens with our demo data. 

I would want to wait until that issue gets addressed by our engineers before merging this. I will follow up in the next couple of days

**Comment by sdzhong** [comment]
Hey @serglom21 

> I do see something not working as expected with the [products_request.duration](https://sergios-test-org.sentry.io/metrics/?interval=4h&project=4506028206850048&statsPeriod=14d&widgets=%5B%7B%22mri%22%3A%22d%3Acustom%2Fproducts_request.duration%40millisecond%22%2C%22op%22%3A%22sum%22%2C%22query%22%3A%22%22%2C%22powerUserMode%22%3Afalse%2C%22type%22%3A1%2C%22id%22%3A0%2C%22displayType%22%3A%22line%22%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%2C%22isHidden%22%3Afalse%2C%22overlays%22%3A%5B%22samples%22%5D%7D%5D) metric, where the description for that span is not showing up - I will check on that with the team and follow up!

This should be fixed in https://github.com/getsentry/sentry-java/releases/tag/7.8.0, (`4.5.0` of the gradle plugin)

**Comment by sdzhong** [comment]
Thanks for your work here @serglom21! Metrics will be instrumented differently (and connected to spans), so this PR is no longer applicable.

**Pull request closed without merging**
