### PR TITLE
update gradle plugin to 4.10.0

### PR DESCRIPTION
**Pull request by sdzhong**

### CODE REVIEW

**Comment by sdzhong** [comment]
Resolves https://github.com/sentry-demos/android/issues/139, see [Trace](https://demo.sentry.io/performance/trace/2480796803c84881867bb95396c0cfa1/?end=2024-08-02T15%3A50%3A00&field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&node=txn-53343d59df1a41fe85d60820f963727b&pageEnd=2024-08-02T15%3A50%3A00.000&pageStart=2024-08-02T15%3A21%3A49.000&project=1801383&query=release%3Acom.example.vu.android%402.11.0%2B46&sort=-timestamp&source=discover&start=2024-08-02T15%3A21%3A49&timestamp=1722613440&yAxis=count%28%29)

image

**Comment by sdzhong** [comment]
Network Event is not appearing: events [7.12.0](https://demo.sentry.io/issues/5669560804/?project=1801383&query=release%3Acom.example.vu.android%402.11.0%2B46&referrer=issue-stream&sort=trends&statsPeriod=6h&stream_index=3) (gradle plugin v4.10.0) vs [7.6.0](https://demo.sentry.io/issues/5560253118/?project=1801383&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=6h&stream_index=2)

image

**Comment by sdzhong** [comment]
> Network Event breadcrumb is not appearing: events [7.12.0](https://demo.sentry.io/issues/5669560804/?project=1801383&query=release%3Acom.example.vu.android%402.11.0%2B46&referrer=issue-stream&sort=trends&statsPeriod=6h&stream_index=3) (gradle plugin v4.10.0) vs [7.6.0](https://demo.sentry.io/issues/5560253118/?project=1801383&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=6h&stream_index=2)
> 
> image

This appears to be a false alarm. I see some `Network Event` breadcrumbs by retrying without changing anything. https://demo.sentry.io/issues/5669560804/events/339e8772d1434647a83522cd0600d24e/

**Comment by sdzhong** [comment]
Thread [discuss-demo](https://sentry.slack.com/archives/C05FA9D2PDM/p1723059990195749)

Aug 7, 2024
Simon (SE):

> Hey team, 
> @Person_1  and I are wrapping up the Android :android: SDK upgrade before cutting a new release. Session Replay beta is available in the latest SDK version, and wanted to check with the team here: Do we want to have Session Replay enabled (and if so, at what %).
> Some observations I've had, when enabling Session Replay are:
> There seems to be additional overhead
> [The Replay video](https://%2A%2A%2A%2A%2A%2A.sentry.io/replays/de9364892d0344d09f8c20eca38f214b/?project=******&query=&referrer=%2Freplays%2F&statsPeriod=7d&yAxis=count%28%29) isn't visually accurate for the checkout nor user feedback popup, e.g. it shows a stretched User Feedback popup (screenshot)
> The config to enable it are [here](https://github.com/sentry-demos/android/pull/144/files#diff-2eab8c271979acb276defe44989d9f69c9f0e9b2703d42de7149842bfd310a70), where we've set the setSessionSampleRate(1.0) and setErrorSampleRate(1.0). Should it be enabled and/or should the sample rates be adjusted?

image

Simon (SE):

> CC @neil (SE) @Kosty (SE)

Kosty (SE):

> IMO if it's buggy in a way that will be obvious in a demo, probably let's hold off.
> What would be the rationale for a sample rate between 1.0 and 0.0?

Simon (SE):

> It could be nice to have a mobile/Android Session Replay available when customers are interested in seeing what's available atm (even while it's in beta).
> The standard Android 3.x demo flow isn't affected by this, so having a lower sample rate (even 0.01) would mean we have a slow drip of new Replays appearing.

Neil (SE):  

> i would set (session) sampleRate to 1.0, just so we can make sure there is a session-replay for every event/span/etc. that we are looking at it
> [^ we don't generate that much traffic via tda, so should be fine 🙂 ]

**Comment by sdzhong** [comment]
resolves https://github.com/sentry-demos/android/issues/142

**Comment by bruno-garcia** [comment]
What supposedly the feedback form was: 
image


Strange since we take screenshots of the app, not sure how something like this could happen.

Is it possible it recorded a different instance/device run?

**Comment by bruno-garcia** [comment]
Bug is reported here:
* https://github.com/getsentry/sentry-java/issues/3574

**Pull request merged**
