### PR TITLE
point to the latest release

### PR DESCRIPTION
**Pull request by bruno-garcia**
/cc @marandaneto 
I can't tag reviewers

### CODE REVIEW

**Comment by thinkocapo** [comment]
thanks @bruno-garcia I sent you an invite for the org. Did you receive it? Let me know if it helps with adding reviewers.

**Comment by bruno-garcia** [comment]
Got it @thinkocapo thanks

**Comment by bruno-garcia** [comment]
I don't have write access to this repo though. Maybe me make org admin?

**Comment by marandaneto** [comment]
> I don't have write access to this repo though. Maybe me make org admin?

same

**Pull request merged**
