### PR TITLE
Add delay between versions and slow db query

### PR DESCRIPTION
**Pull request by stefanosiano**
Added a delay based on versions: even versions have a delay of 1 second, to show the difference between releases in the starfish screen
Added a slow db query on start

[Here](https://demo.sentry.io/performance/android:3e05ea324619450bb21c8c2619ae8d39/?project=1801383&query=&referrer=performance-transaction-summary&showTransactions=recent&statsPeriod=1h&transaction=EmpowerPlantActivity&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29) is a transaction example (especially for the db span)

### CODE REVIEW

**Comment by sdzhong** [comment]
The slowQuery() may have caused the EmpowerPlantActivity transaction to be too slow.

I made a copy of the slow-db-query branch as https://github.com/sentry-demos/android/tree/slow-db-query-sz and ran the automation/pytest with the [generated apk's](https://github.com/sentry-demos/android/commit/492af20a0e8e85ac3c70c1105ec027a49f383889) and generated [these EmpowerPlantActivity transactions](https://demo.sentry.io/discover/homepage/?display=default&end=2023-12-05T02%3A55%3A33.000&field=versionName&field=avg%28transaction.duration%29&field=count%28%29&name=All+Events&project=1801383&query=+title%3AEmpowerPlantActivity&sort=-versionName&start=2023-12-05T01%3A40%3A33.000&yAxis=avg%28transaction.duration%29&yAxis=count%28%29). The transactions are approx 24s long (versus approx 9s in the main branch), which is edging towards too long. 

- My PR https://github.com/sentry-demos/android/pull/104 adds about 2s to the `product_processing` span 
- There's a 30s limit on capturing profiles

May slowQuery() be less slow--perhaps keep the EmpowerPlantActivity transactions (via pytest) closer to 15s?

**Comment by stefanosiano** [comment]
@sdzhong i reduced the time. In case you need to adjust it, you can just change the [loop count](https://github.com/sentry-demos/android/pull/105/files#diff-a81516de6a178b3998818ac5242abbd8a9d03b356015bf7956bb453a2f265a88R46) to whatever you prefer.

**Comment by sdzhong** [comment]
Looks great!

Validated the transaction duration change according to version 
image


image


Validated no regressions
1. [Flagship Error](https://demo.sentry.io/issues/4701770357/events/9f07878da4534b8898d893f69f994466/)
2. [Flagship Error’s Transaction](https://demo.sentry.io/performance/android:e054d89a828a4a0ba1a81d700ce80592/?project=1801383&query=is%3Aunresolved+versionName%3A2.9.1&referrer=issue-stream&statsPeriod=1h&stream_index=6&transaction=checkout+%5Bandroid%5D)
3. [Flagship Transaction](https://demo.sentry.io/performance/android:9aff023c6d4445f3ace04c14a24a6cec/?project=1801383&query=is%3Aunresolved+versionName%3A2.9.1&referrer=issue-stream&statsPeriod=1h&stream_index=9&transaction=EmpowerPlantActivity)
4. Performance Issues - [DB on Main Thread](https://demo.sentry.io/issues/4699271534/events/9aff023c6d4445f3ace04c14a24a6cec/), [File IO on Main Thread](https://demo.sentry.io/issues/4123283095/events/9aff023c6d4445f3ace04c14a24a6cec/), [Regex on Main Thread](https://demo.sentry.io/issues/4457154922/events/4a94558cd35d459cad7bc945c450b244/), [Image Decoding on Main Thread](https://demo.sentry.io/issues/4457867370/events/9bef98a052114772829d175c53c02283/), [JSON Decoding on Main Thread](https://demo.sentry.io/issues/4458151623/events/baf426b00a5a4a61bbf9f260faceb7c3/)

**Review by sdzhong — APPROVED** [review]

**Comment by sdzhong** [comment]
Fixed by https://github.com/sentry-demos/android/pull/105

**Pull request merged**
